### ISSUE TITLE
make this heroku friendly

### ISSUE THREAD

**Issue by diwu1989** [quantopian/coal-mine#3]
This should be something that's deployable on Heroku.

Heroku's platform has mongodb providers and email providers, so it should be technical possible.

**Comment by jikamens** [comment]
Seems like a good idea. I don't have time to look at it right now, but I will leave the issue open and try to get to it at some point. Needless to say, a PR would always be welcome. ;-)

**Comment by jikamens** [comment]
This is done. See "Deploying the Server to Heroku" in the README. Please file issues if you run into them!
