### ISSUE TITLE
Probably not a good idea to do SSL in server

### ISSUE THREAD

**Issue by diwu1989** [quantopian/coal-mine#5]
Noticed that you have
```
To Do:
...
SSL support in server
```
I don't think it's a good idea do SSL support in a web application because production web applications are deployed behind a reverse proxy that is optimized for SSL termination, such as Nginx.

You also want to:
```
Do one, simple thing well. There are several similar projects out there that do more than this project attempts to do.
```
therefore, I propose striking SSL termination out of the TODO section

**Comment by jikamens** [comment]
Hi,

The README also says:

>Minimize external dependencies. If something is simple and straightforward to do ourselves, don't use a third-party package just for the sake of using a third-party package.

SSL is easy to do, and Coal Mine is a trivial enough application that it by no means _needs_ to be run behind a reverse proxy to support SSL. Therefore, adding SSL support to the application is a good idea which I hope to eventually have time to implement (or I hope someone else does it and submits a PR!).
